"""Add script and voice models

Revision ID: 231dbb2d55b6
Revises: c9b54f8128c0
Create Date: 2019-01-17 02:21:01.135030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '231dbb2d55b6'
down_revision = 'c9b54f8128c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('script',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('src_title', sa.String(length=64), nullable=True),
    sa.Column('src_part', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=128), nullable=True),
    sa.Column('duration', sa.Interval(), nullable=True),
    sa.Column('script_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['script.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voice')
    op.drop_table('script')
    # ### end Alembic commands ###
